### ISSUE TITLE
Resuming from pause button breaks game

### ISSUE THREAD

**Issue by sapple-code** [moonrabbit-kingdom/moon-mage#2]
Player can't move after resuming from pause (and I think as well from restarting the game)

**Comment by trjohnst** [comment]
I've seen this too. I think it has to do with the play/pause throttle I have but I'm not sure.

I've noticed that if pause is pressed again and continue is then pressed, play goes back to normal.

**Comment by trjohnst** [comment]
Looks like it happened after I refactored pause out of the level code.

It's fixed as part of [ea3cd78](https://github.com/moonrabbit-kingdom/moon-mage/commit/ea3cd784091a8574fedd668d7fae6ea54037a22c)
