### ISSUE TITLE
Incorporating Playtest Feedback

### ISSUE THREAD

**Issue by splayemu** [moonrabbit-kingdom/moon-mage#4]
Do:
* ~~Boxes (or whole level) should reset on death~~ (resolved as of 9f245a2)
* ~~Expand distance between last two ledges (they are jumpable)~~ 8b0e570c

Discuss:
* ~~Moon movement WASD and player movement at same time~~ #12
* ~~I think the moon shouldn't "reset" position because you always need it ahead of you if anything it should reset on the right side of the screen~~ #13

Future:
* ~~surfing the waves~~ ([project 3](https://github.com/moonrabbit-kingdom/moon-mage/projects/3))

**Comment by trjohnst** [comment]
Resolved whole level reset as of 9f245a2

**Comment by splayemu** [comment]
Ledges are not jumpable as of 8b0e570c

**Comment by trjohnst** [comment]
Moving remaining items to #12 and #13 to discuss individually. Closing this issue.
