### ISSUE TITLE
Future Suggestions

### ISSUE THREAD

**Issue by ChairGTables** [moonrabbit-kingdom/moon-mage#5]
- ~~Too floaty; perhaps making the downward speed faster would eliminate this feeling~~ (moved to #14)
- ~~Fighting with enemies might be difficult due to the fact that you cannot move while casting and moving the moon is too slow. Moon spell speed is recommended to be faster~~ (moved to #16)
- ~~Perhaps a running ability might help alleviate the game's slow atmosphere as well~~ (moved to #15)
- ~~Casting the Moon spell needs sound and visual indication; new players are likely to have a hard time on how to make it work~~ (moved to #1)

**Comment by trjohnst** [comment]
A few thoughts:

- Regarding the second point, I think this is somewhat valuable. It makes the player feel a little more squishy like most mages. I suppose we'll see how this plays out when we build enemies.
- Regarding the last point, @ChairGTables would you be able to create a looping "magic" kind of sound that we can enable while moon control is active? Or point us to somewhere we can generate some kind of sound.

**Comment by trjohnst** [comment]
Regarding fighting with enemies: what if touching an enemy jumps into a mini-game or turn based combat system?

**Comment by ChairGTables** [comment]
Turning it into a mini-game will destroy the purpose of our physics focused gameplay so I suggest not to
I might be able to make a looping magic noise; I think the sound of a fridge turning on would be perfect for it along with other electronic turning on noises lol

**Comment by trjohnst** [comment]
Yea I like that, some kind of low humming noise sounds good.

**Comment by ChairGTables** [comment]
Perhaps I suck at getting the sound of the fridge so I tried making these sounds instead. They sound fine to me but I'm curious to see if they actually fit the game.
Start of Spell: https://pomf.pyonpyon.moe/xtnpyb.wav
Looping Sound: https://pomf.pyonpyon.moe/akpvfr.wav

**Comment by trjohnst** [comment]
Moving items in this list into individual issues. Marking this as closed.
